In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [2]:
df = pd.read_csv("TD_2023.11.22_08.37.40.csv")

In [3]:
df.head(15)

,pl_name,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbperlim,pl_rade,pl_radeerr1,pl_radeerr2,pl_radelim,pl_orbeccen,...,pl_ratror,pl_ratrorerr1,pl_ratrorerr2,pl_ratrorlim,sy_vmag,sy_vmagerr1,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2
0,55 Cnc e,2.808000,2.000000e-03,-2.000000e-03,0.0,NaN,NaN,NaN,NaN,0.174,...,NaN,NaN,NaN,NaN,5.95084,0.023,-0.023,4.015,0.036,-0.036
1,55 Cnc e,0.736547,1.300000e-06,-1.400000e-06,0.0,1.875,0.029,-0.029,0.0,0.050,...,0.01820,0.00020,-0.00020,0.0,5.95084,0.023,-0.023,4.015,0.036,-0.036
2,55 Cnc e,0.736548,1.600000e-06,-1.200000e-06,0.0,NaN,NaN,NaN,NaN,0.028,...,NaN,NaN,NaN,NaN,5.95084,0.023,-0.023,4.015,0.036,-0.036
3,55 Cnc e,0.736539,7.000000e-06,-7.000000e-06,0.0,1.910,0.080,-0.080,0.0,NaN,...,0.01870,0.00070,-0.00070,0.0,5.95084,0.023,-0.023,4.015,0.036,-0.036
4,55 Cnc e,2.796740,1.000000e-04,-1.000000e-04,0.0,NaN,NaN,NaN,NaN,0.264,...,NaN,NaN,NaN,NaN,5.95084,0.023,-0.023,4.015,0.036,-0.036
5,55 Cnc e,0.736542,2.500000e-06,-2.800000e-06,0.0,NaN,NaN,NaN,NaN,NaN,...,0.01936,0.00079,-0.00075,0.0,5.95084,0.023,-0.023,4.015,0.036,-0.036
6,55 Cnc e,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5.95084,0.023,-0.023,4.015,0.036,-0.036
7,55 Cnc e,0.736545,1.400000e-06,-1.500000e-06,0.0,NaN,NaN,NaN,NaN,0.036,...,NaN,NaN,NaN,NaN,5.95084,0.023,-0.023,4.015,0.036,-0.036
8,55 Cnc e,0.736546,1.010000e-06,-1.010000e-06,0.0,1.915,0.214,-0.214,0.0,NaN,...,NaN,NaN,NaN,NaN,5.95084,0.023,-0.023,4.015,0.036,-0.036
9,55 Cnc e,0.736547,1.300000e-06,-1.300000e-06,0.0,1.947,0.038,-0.038,0.0,NaN,...,0.01820,0.00020,-0.00020,0.0,5.95084,0.023,-0.023,4.015,0.036,-0.036
10,55 Cnc e,0.736546,1.600000e-07,-1.600000e-07,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,5.95084,0.023,-0.023,4.015,0.036,-0.036
11,55 Cnc e,0.736546,3.000000e-06,-3.000000e-06,0.0,2.173,0.097,-0.098,0.0,0.000,...,NaN,NaN,NaN,NaN,5.95084,0.023,-0.023,4.015,0.036,-0.036
12,55 Cnc e,0.737000,NaN,NaN,0.0,1.897,0.044,-0.046,0.0,NaN,...,0.01821,0.00027,-0.00029,0.0,5.95084,0.023,-0.023,4.015,0.036,-0.036
13,55 Cnc e,NaN,NaN,NaN,NaN,1.920,0.080,-0.080,0.0,NaN,...,0.01870,0.00070,-0.00070,0.0,5.95084,0.023,-0.023,4.015,0.036,-0.036
14,55 Cnc e,0.736552,1.500000e-06,-1.500000e-06,0.0,NaN,NaN,NaN,NaN,0.040,...,NaN,NaN,NaN,NaN,5.95084,0.023,-0.023,4.015,0.036,-0.036

In [4]:
print(df.size)
df.shape

1536672

(32014, 48)

In [5]:
df1 = df.dropna()

In [6]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 107 entries, 16 to 32005
Data columns (total 48 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pl_name          107 non-null    object
 1   pl_orbper        107 non-null    float64
 2   pl_orbpererr1    107 non-null    float64
 3   pl_orbpererr2    107 non-null    float64
 4   pl_orbperlim     107 non-null    float64
 5   pl_rade          107 non-null    float64
 6   pl_radeerr1      107 non-null    float64
 7   pl_radeerr2      107 non-null    float64
 8   pl_radelim       107 non-null    float64
 9   pl_orbeccen      107 non-null    float64
 10  pl_orbeccenerr1  107 non-null    float64
 11  pl_orbeccenerr2  107 non-null    float64
 12  pl_orbeccenlim   107 non-null    float64
 13  pl_orbincl       107 non-null    float64
 14  pl_orbinclerr1   107 non-null    float64
 15  pl_orbinclerr2   107 non-null    float64
 16  pl_orbincllim    107 non-null    float64
 17  pl_tranmid       107 non-null    float64
 18  pl_tranmiderr1   107 non-null    float64
 19  pl_tranmiderr2   107 non-null    float64
 20  pl_tranmidlim    107 non-null    float64
 21  ttv_flag         107 non-null    int64
 22  pl_imppar        107 non-null    float64
 23  pl_impparerr1    107 non-null    float64
 24  pl_impparerr2    107 non-null    float64
 25  pl_impparlim     107 non-null    float64
 26  pl_trandep       107 non-null    float64
 27  pl_trandeperr1   107 non-null    float64
 28  pl_trandeperr2   107 non-null    float64
 29  pl_trandeplim    107 non-null    float64
 30  pl_trandur       107 non-null    float64
 31  pl_trandurerr1   107 non-null    float64
 32  pl_trandurerr2   107 non-null    float64
 33  pl_trandurlim    107 non-null    float64
 34  pl_ratdor        107 non-null    float64
 35  pl_ratdorerr1    107 non-null    float64
 36  pl_ratdorerr2    107 non-null    float64
 37  pl_ratdorlim     107 non-null    float64
 38  pl_ratror        107 non-null    float64
 39  pl_ratrorerr1    107 non-null    float64
 40  pl_ratrorerr2    107 non-null    float64
 41  pl_ratrorlim     107 non-null    float64
 42  sy_vmag          107 non-null    float64
 43  sy_vmagerr1      107 non-null    float64
 44  sy_vmagerr2      107 non-null    float64
 45  sy_kmag          107 non-null    float64
 46  sy_kmagerr1      107 non-null    float64
 47  sy_kmagerr2      107 non-null    float64
dtypes: float64(46), int64(1), object(1)
memory usage: 41.0+ KB

In [7]:
column_names = df1.columns
print(column_names)

Index(['pl_name', 'pl_orbper', 'pl_orbpererr1', 'pl_orbpererr2',
       'pl_orbperlim', 'pl_rade', 'pl_radeerr1', 'pl_radeerr2', 'pl_radelim',
       'pl_orbeccen', 'pl_orbeccenerr1', 'pl_orbeccenerr2', 'pl_orbeccenlim',
       'pl_orbincl', 'pl_orbinclerr1', 'pl_orbinclerr2', 'pl_orbincllim',
       'pl_tranmid', 'pl_tranmiderr1', 'pl_tranmiderr2', 'pl_tranmidlim',
       'ttv_flag', 'pl_imppar', 'pl_impparerr1', 'pl_impparerr2',
       'pl_impparlim', 'pl_trandep', 'pl_trandeperr1', 'pl_trandeperr2',
       'pl_trandeplim', 'pl_trandur', 'pl_trandurerr1', 'pl_trandurerr2',
       'pl_trandurlim', 'pl_ratdor', 'pl_ratdorerr1', 'pl_ratdorerr2',
       'pl_ratdorlim', 'pl_ratror', 'pl_ratrorerr1', 'pl_ratrorerr2',
       'pl_ratrorlim', 'sy_vmag', 'sy_vmagerr1', 'sy_vmagerr2', 'sy_kmag',
       'sy_kmagerr1', 'sy_kmagerr2'],
      dtype='object')

In [8]:
df1.head(15)

,pl_name,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbperlim,pl_rade,pl_radeerr1,pl_radeerr2,pl_radelim,pl_orbeccen,...,pl_ratror,pl_ratrorerr1,pl_ratrorerr2,pl_ratrorlim,sy_vmag,sy_vmagerr1,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2
16,55 Cnc e,0.736544,5.200000e-06,-5.200000e-06,0.0,2.080,0.160,-0.170,0.0,0.061,...,0.02020,0.00150,-0.00160,0.0,5.95084,0.023,-0.023,4.015000,0.036,-0.036
43,CoRoT-10 b,13.240600,2.000000e-04,-2.000000e-04,0.0,10.870,0.780,-0.780,0.0,0.530,...,0.12690,0.00380,-0.00380,0.0,15.29300,0.137,-0.137,11.782000,0.021,-0.021
63,CoRoT-16 b,5.352270,2.000000e-04,-2.000000e-04,0.0,13.110,1.790,-1.570,0.0,0.330,...,0.10100,0.00460,-0.00460,0.0,16.05200,0.217,-0.217,12.847000,0.037,-0.037
154,CoRoT-9 b,95.273800,1.400000e-03,-1.400000e-03,0.0,11.770,0.450,-0.450,0.0,0.110,...,0.11500,0.00100,-0.00100,0.0,13.63700,0.137,-0.137,11.688000,0.023,-0.023
439,HAT-P-14 b,4.627669,5.000000e-06,-5.000000e-06,0.0,12.890,0.583,-0.583,0.0,0.107,...,0.08050,0.00150,-0.00150,0.0,9.98800,0.004,-0.004,8.851000,0.019,-0.019
453,HAT-P-16 b,2.775960,3.000000e-06,-3.000000e-06,0.0,14.448,0.740,-0.740,0.0,0.036,...,0.10710,0.00140,-0.00140,0.0,10.91100,0.008,-0.008,9.553001,0.020,-0.020
534,HAT-P-24 b,3.355240,7.000000e-06,-7.000000e-06,0.0,13.922,0.751,-0.751,0.0,0.067,...,0.09700,0.00120,-0.00120,0.0,11.76200,0.022,-0.022,10.543000,0.020,-0.020
551,HAT-P-26 b,4.234516,1.500000e-05,-1.500000e-05,0.0,6.333,0.807,-0.359,0.0,0.124,...,0.07370,0.00120,-0.00120,0.0,11.75700,0.025,-0.025,9.581000,0.023,-0.023
568,HAT-P-29 b,5.723390,1.300000e-05,-1.300000e-05,0.0,11.926,0.841,-0.762,0.0,0.075,...,0.08850,0.00120,-0.00110,0.0,11.82500,0.021,-0.021,10.297000,0.020,-0.020
597,HAT-P-31 b,5.005425,9.100000e-05,-9.200000e-05,0.0,11.990,2.690,-1.790,0.0,0.245,...,0.08000,0.02200,-0.01500,0.0,11.66700,0.015,-0.015,10.083000,0.021,-0.021
609,HAT-P-32 b,2.150008,1.300000e-07,-1.300000e-07,0.0,22.194,0.504,-0.504,0.0,0.159,...,0.14886,0.00056,-0.00054,0.0,11.43900,0.015,-0.015,9.990000,0.022,-0.022
636,HAT-P-35 b,3.646706,2.100000e-05,-2.100000e-05,0.0,14.930,1.098,-1.098,0.0,0.025,...,0.09540,0.00270,-0.00270,0.0,12.38900,0.092,-0.092,11.030000,0.021,-0.021
640,HAT-P-36 b,1.327347,3.300000e-07,-3.300000e-07,0.0,15.211,0.392,-0.381,0.0,0.063,...,0.12600,0.00110,-0.00110,0.0,12.14600,0.025,-0.025,10.603000,0.021,-0.021
651,HAT-P-37 b,2.797436,7.000000e-06,-7.000000e-06,0.0,13.204,0.863,-0.863,0.0,0.058,...,0.13780,0.00300,-0.00300,0.0,13.42700,0.126,-0.126,11.667000,0.020,-0.020
855,HAT-P-9 b,3.922811,1.020000e-06,-1.020000e-06,0.0,15.614,0.751,-0.729,0.0,0.084,...,0.10696,0.00086,-0.00087,0.0,12.34400,0.047,-0.047,11.015000,0.021,-0.021

In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [10]:
# Select relevant features and target variable
features = df1[['pl_orbper', 'pl_rade', 'pl_orbeccen', 'pl_orbincl', 'pl_tranmid', 'pl_imppar', 'pl_trandep', 'pl_trandur', 'pl_ratdor', 'pl_ratror', 'sy_vmag', 'sy_kmag']]
target = df1['ttv_flag']

In [18]:
features.columns

Index(['pl_orbper', 'pl_rade', 'pl_orbeccen', 'pl_orbincl', 'pl_tranmid',
       'pl_imppar', 'pl_trandep', 'pl_trandur', 'pl_ratdor', 'pl_ratror',
       'sy_vmag', 'sy_kmag'],
      dtype='object')

In [11]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

In [12]:
# Standardize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [13]:
# Train a RandomForestClassifier
model = RandomForestClassifier(random_state=42)
model.fit(X_train_scaled, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test_scaled)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")

Accuracy: 1.00
Precision: 0.00
Recall: 0.00
F1 Score: 0.00

c:\Users\hp\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\hp\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 due to no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\hp\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\metrics\_classification.py:1757: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, "true nor predicted", "F-score is", len(true_sum))

In [14]:
# Sample input data
sample_input = pd.DataFrame({
    'pl_orbper': [10.0],
    'pl_rade': [1.5],
    'pl_orbeccen': [0.1],
    'pl_orbincl': [89.0],
    'pl_tranmid': [2459000.0],
    'pl_imppar': [0.02],
    'pl_trandep': [0.01],
    'pl_trandur': [2.0],
    'pl_ratdor': [0.01],
    'pl_ratror': [0.1],
    'sy_vmag': [10.0],
    'sy_kmag': [8.0]
})

# Standardize the sample input
sample_input_scaled = scaler.transform(sample_input)

# Make predictions using the trained model
sample_output = model.predict(sample_input_scaled)

print("Sample Input:")
print(sample_input)
print("\nPredicted Output:")
print(sample_output)

Sample Input:
   pl_orbper  pl_rade  pl_orbeccen  pl_orbincl  pl_tranmid  pl_imppar  \
0       10.0      1.5          0.1        89.0   2459000.0       0.02

   pl_trandep  pl_trandur  pl_ratdor  pl_ratror  sy_vmag  sy_kmag
0        0.01         2.0       0.01        0.1     10.0      8.0

Predicted Output:
[0]

In [15]:
y_train.nunique()

2

In [16]:
# Select only rows where ttv_flag is 1
class_1_data = df1[df1['ttv_flag'] == 1]

# Display the dataset for class 1
print("Dataset for Class 1:")
print(class_1_data)

Dataset for Class 1:
           pl_name  pl_orbper  pl_orbpererr1  pl_orbpererr2  pl_orbperlim  \
2247      K2-266 d  14.697000   3.400000e-04  -3.500000e-04           0.0
2250      K2-266 e  19.482000   1.200000e-03  -1.200000e-03           0.0
4985   Kepler-11 b  10.303900   6.000000e-04  -1.000000e-03           0.0
5000   Kepler-11 c  13.024100   1.300000e-03  -8.000000e-04           0.0
5011   Kepler-11 d  22.684500   9.000000e-04  -9.000000e-04           0.0
5027   Kepler-11 e  31.999600   8.000000e-04  -1.200000e-03           0.0
5043   Kepler-11 f  46.688800   2.700000e-03  -3.200000e-03           0.0
31250    WASP-18 b   0.941452   2.400000e-07  -2.400000e-07           0.0
31256    WASP-18 b   0.941453   7.800000e-07  -8.600000e-07           0.0

       pl_rade  pl_radeerr1  pl_radeerr2  pl_radelim  pl_orbeccen  ...  \
2247     2.930        0.140       -0.120         0.0      0.04700  ...
2250     2.730        0.140       -0.110         0.0      0.04300  ...
4985     1.800        0.030       -0.050         0.0      0.04500  ...
5000     2.870        0.050       -0.060         0.0      0.02600  ...
5011     3.120        0.060       -0.070         0.0      0.00400  ...
5027     4.190        0.070       -0.090         0.0      0.01200  ...
5043     2.490        0.040       -0.070         0.0      0.01300  ...
31250   13.899        0.886       -0.886         0.0      0.00510  ...
31256   14.202        0.695       -0.504         0.0      0.00848  ...

       pl_ratror  pl_ratrorerr1  pl_ratrorerr2  pl_ratrorlim  sy_vmag  \
2247     0.03827        0.00071       -0.00057           0.0   11.625
2250     0.03564        0.00067       -0.00061           0.0   11.625
4985     0.01563        0.00018       -0.00023           0.0   13.817
5000     0.02496        0.00015       -0.00019           0.0   13.817
5011     0.02714        0.00018       -0.00019           0.0   13.817
5027     0.03643        0.00021       -0.00028           0.0   13.817
5043     0.02169        0.00026       -0.00026           0.0   13.817
31250    0.10180        0.00110       -0.00110           0.0    9.280
31256    0.09576        0.00105       -0.00063           0.0    9.280

       sy_vmagerr1  sy_vmagerr2  sy_kmag  sy_kmagerr1  sy_kmagerr2
2247         0.046       -0.046    8.897        0.023       -0.023
2250         0.046       -0.046    8.897        0.023       -0.023
4985         0.092       -0.092   12.180        0.020       -0.020
5000         0.092       -0.092   12.180        0.020       -0.020
5011         0.092       -0.092   12.180        0.020       -0.020
5027         0.092       -0.092   12.180        0.020       -0.020
5043         0.092       -0.092   12.180        0.020       -0.020
31250        0.030       -0.030    8.131        0.027       -0.027
31256        0.030       -0.030    8.131        0.027       -0.027

[9 rows x 48 columns]

In [16]:
import joblib

# Save the trained model to a file
model_filename = 'random_forest_model.joblib'
joblib.dump(model, model_filename)

print(f"Model saved to {model_filename}")

Model saved to random_forest_model.joblib

In [18]:
# Select rows where ttv_flag is 0
class_0_data = df1[df1['ttv_flag'] == 0]

# Print message for class 0
print("Exoplanets with ttv_flag equal to 0 (not present):")
print(class_0_data[['pl_name', 'ttv_flag']])  # Displaying only 'pl_name' and 'ttv_flag' columns

# Select rows where ttv_flag is 1
class_1_data = df1[df1['ttv_flag'] == 1]

# Print message for class 1
print("\nExoplanets with ttv_flag equal to 1 (present):")
print(class_1_data[['pl_name', 'ttv_flag']])  # Displaying only 'pl_name' and 'ttv_flag' columns

Exoplanets with ttv_flag equal to 0 (not present):
           pl_name  ttv_flag
16        55 Cnc e         0
43      CoRoT-10 b         0
63      CoRoT-16 b         0
154      CoRoT-9 b         0
439     HAT-P-14 b         0
...            ...       ...
31289    WASP-19 b         0
31793  WASP-77 A b         0
31814     WASP-8 b         0
31825    WASP-80 b         0
32005       XO-7 b         0

[98 rows x 2 columns]

Exoplanets with ttv_flag equal to 1 (present):
           pl_name  ttv_flag
2247      K2-266 d         1
2250      K2-266 e         1
4985   Kepler-11 b         1
5000   Kepler-11 c         1
5011   Kepler-11 d         1
5027   Kepler-11 e         1
5043   Kepler-11 f         1
31250    WASP-18 b         1
31256    WASP-18 b         1

In [ ]:
spectra = pd.read_csv('table.csv')

In [12]:
spectra.head(15)

,PL_NAME,SPEC_TYPE,MINWAVELNG,MAXWAVELNG,MINTRANMID,MAXTRANMID,NOTE
0,TRAPPIST-1 c,Emission,15.000,15.000,NaN,NaN,NaN
1,WASP-36 b,Emission,2.159,2.159,NaN,NaN,Table 2
2,WASP-46 b,Emission,2.159,2.159,NaN,NaN,Table 2
3,WASP-4 b,Emission,2.159,2.159,NaN,NaN,Table 2
4,WASP-5 b,Emission,2.159,2.159,NaN,NaN,Table 2
5,WASP-18 b,Emission,2.159,2.159,NaN,NaN,Table 2
6,WASP-19 b,Emission,2.144,2.144,NaN,NaN,Table 3
7,WASP-43 b,Emission,2.144,2.144,NaN,NaN,Table 3
8,WASP-19 b,Transmission,0.866,0.866,2.456291e+06,2.456291e+06,NaN
9,WASP-19 b,Emission,0.866,0.866,NaN,NaN,eclipse depth taken from Abstract
10,HAT-P-32 b,Emission,3.600,4.500,NaN,NaN,Table 2
11,HAT-P-32 b,Emission,1.635,2.150,NaN,NaN,Table 2
12,WASP-3 b,Emission,2.150,2.150,NaN,NaN,NaN
13,CoRoT-1 b,Emission,1.635,1.635,NaN,NaN,NaN
14,XO-2 N b,Transmission,0.360,0.440,2.455932e+06,2.457062e+06,NaN

In [13]:
df3 = spectra.dropna()

In [14]:
df3.head(15)

,PL_NAME,SPEC_TYPE,MINWAVELNG,MAXWAVELNG,MINTRANMID,MAXTRANMID,NOTE
117,WASP-17 b,Transmission,0.385,0.56,2456086.5,2456086.5,Reduced and Fitted Using Iraclis - visit 1
118,WASP-17 b,Transmission,0.570,0.87,2456370.5,2456370.5,Reduced and Fitted Using Iraclis - visit 3
119,WASP-17 b,Transmission,0.385,0.56,2456366.5,2456366.5,Reduced and Fitted Using Iraclis - visit 2